# Use root/example as user/password credentials
version: '3.8'

services:

  postgres:
    image: postgres:alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
